# set base image (host OS)
FROM mewc-flow-app

# set the working directory in the container
WORKDIR /code

# copy the content of the local src directory to the working directory
COPY src/ .

# install dependencies
RUN pip install pytest

# copy code
COPY src/ /code

ENV PYTHONPATH="${PYTHONPATH}:/code"

# Run the tests using unittest
CMD ["python", "-m", "unittest", "discover", "-s", "test", "-p", "*.py"]